[package]
name = "psn_peer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-dnssd = "0.5.0"
bytes = "1.2.1"
futures = "0.3.24"
tokio = { version = "1.21.0", features = ["full"] }
